/**
 * generated by Xtext 2.25.0
 */
package fr.n7.pDL1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Need</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.Need#getNbResources <em>Nb Resources</em>}</li>
 *   <li>{@link fr.n7.pDL1.Need#getResource <em>Resource</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getNeed()
 * @model
 * @generated
 */
public interface Need extends EObject
{
  /**
   * Returns the value of the '<em><b>Nb Resources</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb Resources</em>' attribute.
   * @see #setNbResources(int)
   * @see fr.n7.pDL1.PDL1Package#getNeed_NbResources()
   * @model
   * @generated
   */
  int getNbResources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Need#getNbResources <em>Nb Resources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb Resources</em>' attribute.
   * @see #getNbResources()
   * @generated
   */
  void setNbResources(int value);

  /**
   * Returns the value of the '<em><b>Resource</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' reference.
   * @see #setResource(Resource)
   * @see fr.n7.pDL1.PDL1Package#getNeed_Resource()
   * @model
   * @generated
   */
  Resource getResource();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Need#getResource <em>Resource</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' reference.
   * @see #getResource()
   * @generated
   */
  void setResource(Resource value);

} // Need
