/**
 * generated by Xtext 2.25.0
 */
package fr.n7.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.Resource#getNbAvailableResources <em>Nb Available Resources</em>}</li>
 *   <li>{@link fr.n7.pDL1.Resource#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getResource()
 * @model
 * @generated
 */
public interface Resource extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Nb Available Resources</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb Available Resources</em>' attribute.
   * @see #setNbAvailableResources(int)
   * @see fr.n7.pDL1.PDL1Package#getResource_NbAvailableResources()
   * @model
   * @generated
   */
  int getNbAvailableResources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Resource#getNbAvailableResources <em>Nb Available Resources</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb Available Resources</em>' attribute.
   * @see #getNbAvailableResources()
   * @generated
   */
  void setNbAvailableResources(int value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL1.PDL1Package#getResource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.Resource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Resource
